# Default Training Configuration
# This configuration defines the default training parameters

# Training parameters
num_epochs: 10
batch_size: 32
learning_rate: 1e-4
weight_decay: 0.01

# Optimizer
optimizer: "adamw"
betas: [0.9, 0.999]

# Scheduler
scheduler: "warmup_cosine"
warmup_steps: 1000
total_steps: 10000
min_lr: 0.0

# Training settings
gradient_clip: 1.0
seed: 42
device: "cuda"

# Logging
log_interval: 100

# Model saving
save_model: true
save_path: "models/best_model.pt"
save_best: true
best_model_path: "models/best_model.pt"
save_checkpoints: true
checkpoint_interval: 5 